AWSTemplateFormatVersion: 2010-09-09
Description: Deploys Amazon EMR cluster and associated resources

Parameters:
  EC2KeyPair:
    Description: Amazon EC2 Key Pair
    Type: 'AWS::EC2::KeyPair::KeyName'
  DataBucketName:
    Type: String
    Description: S3 Data bucket name
  DataBucketArn:
    Type: String
    Description: S3 Data bucket ARN
  KdcAdminPassword:
    Type: String
    NoEcho: 'true'
    AllowedPattern: >-
      (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    Description: >-
      Must be at least 8 characters containing letters, numbers and symbols -
      Eg: Password@123
    Default: Password@123
  ReleaseLabel:
    Type: String
    Default: emr-5.33.1
    AllowedValues:
      - emr-5.33.1
      - emr-5.33.0
      - emr-5.32.0
      - emr-5.31.0
    Description: Selet an EMR Version
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: Select a VPC in which to deploy EMR cluster instances
  VpcSubnet:
    Type: 'AWS::EC2::Subnet::Id'
    Description: Subnet to be used for Amazon EMR cluster.
  InstanceType:
    Type: String
    Default: m5.xlarge
    Description: EMR Cluster Instance Types for both Master and Core
    AllowedValues:
      - m5.xlarge
      - m4.xlarge
      - i3.xlarge
      - i3.2xlarge
      - r4.xlarge
  HostedZoneId:
    Description: Select a hosted zone for your domain name
    Type: AWS::Route53::HostedZone::Id
  DomainName:
    Description: >-
      Enter a domain name that will be used to access Zeppelin (e.g. example.com).
      This may be the domain name of the hosted zone selected above (if not in use) or a subdomain of the hosted zone (e.g. zeppelin.example.com)
    Type: String
  PublicSubnet1Id:
    Description: The ID of a Public Subnet in the VPC
    ConstraintDescription: Must be the ID of an existing subnet within the selected VPC.
    Type: AWS::EC2::Subnet::Id
  PublicSubnet2Id:
    Description: The ID of a Public Subnet in the VPC
    ConstraintDescription: Must be the ID of an existing subnet within the selected VPC.
    Type: AWS::EC2::Subnet::Id
  SAMLProviderArn:
    Description: Enter the ARN of the SAML Provider created in AWS IAM
    Type: String

Resources:
  lfSamlPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          Effect: Allow
          Action:
            - 'lakeformation:GetDataAccess'
            - 'lakeformation:GetMetadataAccess'
            - 'glue:CreateDatabase'
            - 'glue:GetUnfiltered*'
            - 'glue:GetTable'
            - 'glue:GetTables'
            - 'glue:GetDatabase'
            - 'glue:GetDatabases'
            - 'glue:GetUserDefinedFunction'
            - 'glue:GetUserDefinedFunctions'
          Resource: '*'
      Roles:
        - !Ref LakeFormationSAMLRole

  LakeFormationSAMLRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Ref SAMLProviderArn
            Action: 'sts:AssumeRoleWithSAML'
          - Effect: Allow
            Principal:
              Service:
                - glue.amazonaws.com
                - lakeformation.amazonaws.com
            Action: 'sts:AssumeRole'

  lfEmrPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - 'ec2:AuthorizeSecurityGroupEgress'
              - 'ec2:AuthorizeSecurityGroupIngress'
              - 'ec2:CancelSpotInstanceRequests'
              - 'ec2:CreateNetworkInterface'
              - 'ec2:CreateSecurityGroup'
              - 'ec2:CreateTags'
              - 'ec2:DeleteNetworkInterface'
              - 'ec2:DeleteSecurityGroup'
              - 'ec2:DeleteTags'
              - 'ec2:DescribeAvailabilityZones'
              - 'ec2:DescribeAccountAttributes'
              - 'ec2:DescribeDhcpOptions'
              - 'ec2:DescribeImages'
              - 'ec2:DescribeInstanceStatus'
              - 'ec2:DescribeInstances'
              - 'ec2:DescribeKeyPairs'
              - 'ec2:DescribeNetworkAcls'
              - 'ec2:DescribeNetworkInterfaces'
              - 'ec2:DescribePrefixLists'
              - 'ec2:DescribeRouteTables'
              - 'ec2:DescribeSecurityGroups'
              - 'ec2:DescribeSpotInstanceRequests'
              - 'ec2:DescribeSpotPriceHistory'
              - 'ec2:DescribeSubnets'
              - 'ec2:DescribeTags'
              - 'ec2:DescribeVpcAttribute'
              - 'ec2:DescribeVpcEndpoints'
              - 'ec2:DescribeVpcEndpointServices'
              - 'ec2:DescribeVpcs'
              - 'ec2:DetachNetworkInterface'
              - 'ec2:ModifyImageAttribute'
              - 'ec2:ModifyInstanceAttribute'
              - 'ec2:RequestSpotInstances'
              - 'ec2:RevokeSecurityGroupEgress'
              - 'ec2:RunInstances'
              - 'ec2:TerminateInstances'
              - 'ec2:DeleteVolume'
              - 'ec2:DescribeVolumeStatus'
              - 'ec2:DescribeVolumes'
              - 'ec2:DetachVolume'
              - 'iam:GetRole'
              - 'iam:GetRolePolicy'
              - 'iam:ListInstanceProfiles'
              - 'iam:ListRolePolicies'
              - 'iam:PassRole'
              - 'sdb:BatchPutAttributes'
              - 'sdb:Select'
              - 'sqs:CreateQueue'
              - 'sqs:Delete*'
              - 'sqs:GetQueue*'
              - 'sqs:PurgeQueue'
              - 'sqs:ReceiveMessage'
              - 'cloudwatch:PutMetricAlarm'
              - 'cloudwatch:DescribeAlarms'
              - 'cloudwatch:DeleteAlarms'
              - 'application-autoscaling:RegisterScalableTarget'
              - 'application-autoscaling:DeregisterScalableTarget'
              - 'application-autoscaling:PutScalingPolicy'
              - 'application-autoscaling:DeleteScalingPolicy'
              - 'application-autoscaling:Describe*'
          - Effect: Allow
            Action: 'iam:CreateServiceLinkedRole'
            Resource: >-
              arn:aws:iam::*:role/aws-service-role/spot.amazonaws.com/AWSServiceRoleForEC2Spot*
            Condition:
              StringLike:
                'iam:AWSServiceName': spot.amazonaws.com
      Roles:
        - !Ref LakeFormationEMRRole

  LakeFormationEMRRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2008-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: elasticmapreduce.amazonaws.com
            Action: 'sts:AssumeRole'

  lfEmrInstanceProfilePolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Resource: '*'
            Action:
              - 'dynamodb:CreateTable'
              - 'dynamodb:BatchGetItem'
              - 'dynamodb:BatchWriteItem'
              - 'dynamodb:PutItem'
              - 'dynamodb:DescribeTable'
              - 'dynamodb:DeleteItem'
              - 'dynamodb:GetItem'
              - 'dynamodb:Scan'
              - 'dynamodb:Query'
              - 'dynamodb:UpdateItem'
              - 'dynamodb:DeleteTable'
              - 'dynamodb:UpdateTable'
              - 'dynamodb:ListTables'
              - 'elasticmapreduce:Describe*'
              - 'elasticmapreduce:ListBootstrapActions'
              - 'elasticmapreduce:ListClusters'
              - 'elasticmapreduce:ListInstanceGroups'
              - 'elasticmapreduce:ListInstances'
              - 'elasticmapreduce:ListSteps'
              - 'kinesis:CreateStream'
              - 'kinesis:DeleteStream'
              - 'kinesis:DescribeStream'
              - 'kinesis:GetRecords'
              - 'kinesis:GetShardIterator'
              - 'kinesis:MergeShards'
              - 'kinesis:PutRecord'
              - 'kinesis:SplitShard'
              - 'rds:Describe*'
              - 'sqs:GetQueueUrl'
              - 'sqs:DeleteMessageBatch'
              - 'sqs:ReceiveMessage'
              - 'sqs:DeleteQueue'
              - 'sqs:SendMessage'
              - 'sqs:CreateQueue'
          - Effect: Allow
            Action:
              - 'cloudwatch:PutMetricData'
            Resource: '*'
          - Effect: Allow
            Action:
              - 'logs:CreateLogGroup'
              - 'logs:CreateLogStream'
              - 'logs:DescribeLogGroups'
              - 'logs:DescribeLogStreams'
              - 'logs:PutLogEvents'
            Resource: '*'
          - Effect: Allow
            Action: 'iam:PassRole'
            Resource: !GetAtt LakeFormationSAMLRole.Arn
          - Effect: Allow
            Action: 'sts:AssumeRole'
            Resource: !GetAtt LakeFormationEMRRole.Arn
          - Effect: Allow
            Action: 'lakeformation:GetTemporaryUserCredentialsWithSAML'
            Resource: '*'
          - Effect: Allow
            Action: 'iam:GetRole'
            Resource:
              - !GetAtt LakeFormationEMRRole.Arn
              - !GetAtt LakeFormationSAMLRole.Arn
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource:
              - 'arn:aws:s3:::emr-okta-blog'
              - >-
                arn:aws:s3:::emr-okta-blog/scripts/*
          - Effect: Allow
            Action:
              - 's3:GetObject'
              - 's3:ListBucket'
            Resource:
              - !Ref DataBucketArn
              - !Sub '${DataBucketArn}/*'
      Roles:
        - !Ref LakeFormationEMRInstanceProfileRole

  LakeFormationEMRInstanceProfileRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: 'sts:AssumeRole'
      ManagedPolicyArns:
        - 'arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore'

  LFEMRInstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      InstanceProfileName: !Sub 'LakeFormationEMRInstanceProfileRole-${AWS::StackName}'
      Path: /
      Roles:
        - !Ref LakeFormationEMRInstanceProfileRole

  LFEMRSecurityConfiguration:
    Type: 'AWS::EMR::SecurityConfiguration'
    Properties:
      Name: !Sub 'LF-EMR-SecurityConfiguration-${AWS::StackName}'
      SecurityConfiguration:
        LakeFormationConfiguration:
          IdpMetadataS3Path: !Sub 's3://${DataBucketName}/IdP-metadata/okta-metadata.xml'
          EmrRoleForUsersARN: !GetAtt LakeFormationEMRRole.Arn
          LakeFormationRoleForSAMLPrincipalARN: !GetAtt LakeFormationSAMLRole.Arn
        AuthenticationConfiguration:
          KerberosConfiguration:
            Provider: ClusterDedicatedKdc
            ClusterDedicatedKdcConfiguration:
              TicketLifetimeInHours: 24

  S3EMRLogsBucket:
    Type: 'AWS::S3::Bucket'
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Join ['-', ['emrblog-logs', !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]

  EMRCluster:
    Type: 'AWS::EMR::Cluster'
    DependsOn:
      - LakeFormationEMRInstanceProfileRole
    Properties:
      Instances:
        AdditionalMasterSecurityGroups:
          - !Ref MasterNodeAdditionalSG
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref InstanceType
          Market: ON_DEMAND
          Name: cfnMaster
        CoreInstanceGroup:
          InstanceCount: 1
          InstanceType: !Ref InstanceType
          Market: ON_DEMAND
          Name: cfnCore
        Ec2SubnetId: !Ref VpcSubnet
        Ec2KeyName: !Ref EC2KeyPair
      Name: !Sub 'LF-EMRCluster-${AWS::StackName}'
      Applications:
        - Name: Hadoop
        - Name: Spark
        - Name: Livy
        - Name: Zeppelin
      Configurations:
        - Classification: spark-hive-site
          ConfigurationProperties:
            hive.metastore.glue.catalogid: !Ref 'AWS::AccountId'
      JobFlowRole: !Ref LFEMRInstanceProfile
      KerberosAttributes:
        KdcAdminPassword: !Ref KdcAdminPassword
        Realm: 'EC2.INTERNAL'
      ServiceRole: !Ref LakeFormationEMRRole
      ReleaseLabel: !Ref ReleaseLabel
      SecurityConfiguration: !Ref LFEMRSecurityConfiguration
      VisibleToAllUsers: true
      LogUri: !Sub 's3://${S3EMRLogsBucket}/'

  fetchIpLambdaPolicy:
    Type: 'AWS::IAM::ManagedPolicy'
    DependsOn: EMRCluster
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Action: 'elasticmapreduce:ListInstances'
            Resource: !Sub 'arn:aws:elasticmapreduce:${AWS::Region}:${AWS::AccountId}:cluster/${EMRCluster}'
            Effect: Allow
          - Action: 'logs:CreateLogGroup'
            Resource: !Sub 'arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*'
            Effect: Allow
          - Action:
              - 'logs:CreateLogStream'
              - 'logs:PutLogEvents'
            Resource:
              - !Sub >-
                arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/lambda/fetchMasterNodeIp-${AWS::StackName}:*
            Effect: Allow
          - Action:
              - 's3:GetObject'
              - 's3:List*'
            Resource:
              - 'arn:aws:s3:::emr-okta-blog'
              - 'arn:aws:s3:::emr-okta-blog/artifacts/*'
            Effect: Allow
      Roles:
        - !Ref fetchIpLambdaExecutionRole

  fetchIpLambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: 'sts:AssumeRole'

  fetchMasterNodeIpLambda:
    Type: 'AWS::Lambda::Function'
    Properties:
      Handler: fetchMasterNodeIp.handler
      FunctionName: !Sub 'fetchMasterNodeIp-${AWS::StackName}'
      Runtime: python3.9
      Code:
        S3Bucket: emr-okta-blog
        S3Key: >-
          artifacts/fetchmasternodeip.py.zip
      Description: 'Fetch master node IP address of EMR Cluster.'
      MemorySize: 128
      Timeout: 60
      Role: !GetAtt fetchIpLambdaExecutionRole.Arn

  customResourceForMasterNodeIpLambda:
    Type: 'AWS::CloudFormation::CustomResource'
    DependsOn:
      - fetchIpLambdaExecutionRole
      - fetchIpLambdaPolicy
    Version: '1.0'
    Properties:
      ServiceToken: !GetAtt fetchMasterNodeIpLambda.Arn
      StackName: !Ref 'AWS::StackName'
      ClusterId: !Ref EMRCluster

  ACMCertificate: 
    Type: 'AWS::CertificateManager::Certificate'
    Properties: 
      DomainName: !Ref DomainName
      DomainValidationOptions:
        - 
          DomainName: !Ref DomainName
          HostedZoneId: !Ref HostedZoneId
      ValidationMethod: DNS

  ZeppelinTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties: 
      HealthCheckPath: '/gateway/default/zeppelin/'
      HealthCheckProtocol: "HTTPS"
      Name: !Sub 'emrblog-tg-${AWS::AccountId}'
      Port: 8442
      Protocol: HTTPS
      ProtocolVersion: HTTP1
      Targets:
        - Id: !GetAtt customResourceForMasterNodeIpLambda.MasterNodeIp
      TargetType: ip
      VpcId: !Ref VpcId

  ALBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: 'Security group for ALB'
      SecurityGroupIngress: 
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          Description: Allow public HTTPS access to ALB
        - CidrIp: 0.0.0.0/0
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          Description: Allow public HTTP access to ALB
      SecurityGroupEgress:
        - Description: Allow all outbound traffic
          IpProtocol: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcId

  MasterNodeAdditionalSG:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: 'Security group for Master node to allow access to Zeppelin'
      SecurityGroupIngress: 
        - SourceSecurityGroupId: !Ref ALBSecurityGroup
          IpProtocol: tcp
          FromPort: 8442
          ToPort: 8442
          Description: Allow ALB to access Zeppelin
      SecurityGroupEgress:
        - Description: Allow all outbound traffic
          IpProtocol: -1
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcId
  
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties: 
      IpAddressType: ipv4
      Scheme: internet-facing
      SecurityGroups: 
        - !Ref ALBSecurityGroup
      Subnets: 
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      Type: application

  ALBListenerHTTP:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      DefaultActions: 
        -
          Type: redirect
          RedirectConfig:
            Host: "#{host}"
            Path: "/#{path}"
            Port: 443
            Protocol: HTTPS
            Query: "{query}"
            StatusCode: "HTTP_301"
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP

  ALBListenerHTTPS:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties: 
      Certificates: 
        - 
          CertificateArn: !Ref ACMCertificate
      DefaultActions: 
        -
          Type: forward
          TargetGroupArn: !Ref ZeppelinTG
      LoadBalancerArn: !Ref ALB
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS-1-2-2017-01

  R53RecordSet:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Comment: ALB RecordSet.
      RecordSets:
      - Name: !Ref DomainName
        Type: A
        AliasTarget:
          HostedZoneId: !GetAtt ALB.CanonicalHostedZoneID
          DNSName: !GetAtt ALB.DNSName

Outputs:
  OktaSingleSignOnUrl:
    Description: The value for Single sign on URL, to be updated in Okta
    Value: !Sub 'https://${DomainName}/gateway/knoxsso/api/v1/websso?pac4jCallback=true&client_name=SAML2Client'
  OktaRoleAttribute:
    Description: The value for the attribute statement https://aws.amazon.com/SAML/Attributes/Role, to be updated in Okta
    Value: !Join 
      - ','
      - - !GetAtt 
          - LakeFormationSAMLRole
          - Arn
        - !Ref SAMLProviderArn
  ZeppelinUrl:
    Description: The URL to be used to access Zeppelin
    Value: !Sub 'https://${DomainName}/gateway/default/zeppelin/'
  MasterNodeInstanceId:
    Description: EC2 instance ID of EMR master node
    Value: !GetAtt customResourceForMasterNodeIpLambda.MasterNodeInstanceId