AWSTemplateFormatVersion: 2010-09-09
Description: "Creates resources for blog post - EMR, VPC, LF Databases Etc"

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - DomainName
          - HostedZoneId
      - Label:
          default: Lake Formation Configuration
        Parameters:
          - LFDatabaseName
          - LFTableName
          - LFSAMLUserName
          - OktaAppMetadataURL
          - SAMLProviderName
      - Label:
          default: EMR Configuration
        Parameters:
          - KdcAdminPassword
          - ReleaseLabel
          - InstanceType
          - EC2KeyPair
    ParameterLabels:
      VpcCIDR:
        default: The CIDR range for your VPC
      PublicSubnet1CIDR:
        default: The CIDR range for the first public subnet
      PublicSubnet2CIDR:
        default: The CIDR range for the second public subnet
      PrivateSubnet1CIDR:
        default: The CIDR range for the first private subnet
      PrivateSubnet2CIDR:
        default: The CIDR range for the second private subnet
      DomainName:
        default: DomainName
      HostedZoneId:
        default: HostedZoneId

      LFDatabaseName:
        default: DB name
      LFTableName: 
        default: DBTableName
      LFSAMLUserName:
        default: LFSAMLUserName
      OktaAppMetadataURL: 
        default: OktaAppMetadataURL
      SAMLProviderName:
        default: SAMLProviderName
      EC2KeyPair:
        default: EC2 Key Pair

Parameters:

  #Networking
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.192.10.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.192.11.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.192.21.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  HostedZoneId:
    Description: TBD
    Type: AWS::Route53::HostedZone::Id
  DomainName:
    Description: TBD
    Type: String
  
  #LF
  LFDatabaseName:
    Description: TBD
    Type: String
    Default: emrblogdb
  LFTableName:
    Description: TBD
    Type: String
    Default: cardata
  LFSAMLUserName:
    Description: TBD
    Type: String
    Default: analyst
  OktaAppMetadataURL:
    Description: URL for Okta metadata XML file.
    Type: String
  SAMLProviderName:
    Description: SAML Provider Name Created in AWS
    Type: String
    Default: oktaSAMLProvider

  #EMR
  EC2KeyPair:
    Description: 'Amazon EC2 Key Pair (Optional, for debugging)'
    ConstraintDescription: Must be the name of an existing EC2 KeyPair.
    Type: 'AWS::EC2::KeyPair::KeyName'
  KdcAdminPassword:
    Type: String
    NoEcho: 'true'
    AllowedPattern: >-
      (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    Description: >-
      Must be at least 8 characters containing letters, numbers and symbols -
      Eg: Password@123
    Default: Password@123
  ReleaseLabel:
    Type: String
    Default: emr-5.33.1
    AllowedValues:
      - emr-5.33.1
      - emr-5.33.0
      - emr-5.32.0
      - emr-5.31.0
    Description: EMR Version
  InstanceType:
    Type: String
    Default: m5.xlarge
    Description: EMR Cluster Instance Types for both Master and Core
    AllowedValues:
      - m5.xlarge
      - m4.xlarge
      - i3.xlarge
      - i3.2xlarge
      - r4.xlarge

Resources:
  NetworkingStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://emr-okta-blog.s3.amazonaws.com/templates/networking.yaml'
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

  LakeFormationStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://emr-okta-blog.s3.amazonaws.com/templates/lakeformation.yaml'
      Parameters:
        LFDatabaseName: !Ref LFDatabaseName
        LFTableName: !Ref LFTableName
        LFSAMLUserName: !Ref LFSAMLUserName
        SAMLProviderName: !Sub ${SAMLProviderName}-${AWS::StackName}
        OktaAppMetadataURL: !Ref OktaAppMetadataURL

  EMRStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://emr-okta-blog.s3.amazonaws.com/templates/emr.yaml'
      Parameters:
        EC2KeyPair: !Ref EC2KeyPair
        DataBucketName: !GetAtt 
          - LakeFormationStack
          - Outputs.DataBucketName
        DataBucketArn: !GetAtt 
          - LakeFormationStack
          - Outputs.DataBucketArn
        KdcAdminPassword: !Ref KdcAdminPassword
        ReleaseLabel: !Ref ReleaseLabel
        VPCId: !GetAtt 
          - NetworkingStack
          - Outputs.VPCId
        VPCSubnet: !GetAtt 
          - NetworkingStack
          - Outputs.PrivateSubnet1
        InstanceType: !Ref InstanceType
        HostedZoneId: !Ref HostedZoneId
        DomainName: !Ref DomainName
        PublicSubnet1Id: !GetAtt 
          - NetworkingStack
          - Outputs.PublicSubnet1
        PublicSubnet2Id: !GetAtt 
          - NetworkingStack
          - Outputs.PublicSubnet2
        SAMLProviderName: !Sub ${SAMLProviderName}-${AWS::StackName}

Outputs:
  OktaAttributes:
    Description: >-
      The value for the attribute statement
      https://aws.amazon.com/SAML/Attributes/Role, to be updated in Okta
    Value: !GetAtt 
      - EMRStack
      - Outputs.OktaAttributes
  ZeppelinURL:
    Description: Zeppelin URL
    Value: !GetAtt 
      - EMRStack
      - Outputs.ZeppelinURL