AWSTemplateFormatVersion: 2010-09-09
Description: "Cloudformation template to create Lakeformation resources, EMR cluster and required Networking infra."

Metadata:
  'AWS::CloudFormation::Interface':
    ParameterGroups:
      - Label:
          default: Network Configuration
        Parameters:
          - VpcCIDR
          - PublicSubnet1CIDR
          - PublicSubnet2CIDR
          - PrivateSubnet1CIDR
          - PrivateSubnet2CIDR
          - DomainName
          - HostedZoneId
      - Label:
          default: Lake Formation Configuration
        Parameters:
          - LFDatabaseName
          - LFTableName
          - LFSAMLUserName
          - OktaAppMetadataURL
          - SAMLProviderName
      - Label:
          default: EMR Configuration
        Parameters:
          - KdcAdminPassword
          - ReleaseLabel
          - InstanceType
          - EC2KeyPair
    ParameterLabels:
      VpcCIDR:
        default: The CIDR range for your VPC
      PublicSubnet1CIDR:
        default: The CIDR range for the first public subnet
      PublicSubnet2CIDR:
        default: The CIDR range for the second public subnet
      PrivateSubnet1CIDR:
        default: The CIDR range for the first private subnet
      PrivateSubnet2CIDR:
        default: The CIDR range for the second private subnet
      DomainName:
        default: DomainName
      HostedZoneId:
        default: HostedZoneId

      LFDatabaseName:
        default: DB name
      LFTableName: 
        default: DBTableName
      LFSAMLUserName:
        default: LFSAMLUserName
      OktaAppMetadataURL: 
        default: OktaAppMetadataURL
      SAMLProviderName:
        default: SAMLProviderName
      EC2KeyPair:
        default: EC2 Key Pair

Parameters:
  #Networking
  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this VPC
    Type: String
    Default: 10.192.0.0/16
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  PublicSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.192.10.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  PublicSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.192.11.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  PrivateSubnet1CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the first Availability Zone
    Type: String
    Default: 10.192.20.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  PrivateSubnet2CIDR:
    Description: Please enter the IP range (CIDR notation) for the private subnet in the second Availability Zone
    Type: String
    Default: 10.192.21.0/24
    AllowedPattern: '(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})'
  HostedZoneId:
    Description: Select a hosted zone for your domain name
    Type: AWS::Route53::HostedZone::Id
  DomainName:
    Description: >-
      Enter a domain name that will be used to access Zeppelin (e.g. example.com).
      This may be the domain name of the hosted zone selected above (if not in use) or a subdomain of the hosted zone (e.g. zeppelin.example.com)
    Type: String
  
  #LF
  LFDatabaseName:
    Description: Enter a name for your AWS Glue database
    Type: String
    Default: emrblogdb
  LFTableName:
    Description: Enter a name for your AWS Glue database table
    Type: String
    Default: cardata
  LFSAMLUserName:
    Description: Enter the displayName of the SAML user you created and assigned to your app in Okta
    Type: String
    Default: analyst
  OktaAppMetadataURL:
    Description: Enter the URL of the Okta metadata XML file
    Type: String
  SAMLProviderName:
    Description: Enter a name for the SAML Provider created in AWS IAM
    Type: String
    Default: oktaSAMLProvider

  #EMR
  EC2KeyPair:
    Description: Amazon EC2 Key Pair
    ConstraintDescription: Must be the name of an existing EC2 KeyPair
    Type: 'AWS::EC2::KeyPair::KeyName'
  KdcAdminPassword:
    Type: String
    NoEcho: 'true'
    AllowedPattern: >-
      (?=^.{6,255}$)((?=.*\d)(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[^A-Za-z0-9])(?=.*[a-z])|(?=.*[^A-Za-z0-9])(?=.*[A-Z])(?=.*[a-z])|(?=.*\d)(?=.*[A-Z])(?=.*[^A-Za-z0-9]))^.*
    Description: >-
      Must be at least 8 characters containing letters, numbers and symbols -
      Eg: Password@123
    Default: Password@123
  ReleaseLabel:
    Type: String
    Default: emr-5.33.1
    AllowedValues:
      - emr-5.33.1
      - emr-5.33.0
      - emr-5.32.0
      - emr-5.31.0
    Description: EMR Version
  InstanceType:
    Type: String
    Default: m5.xlarge
    Description: EMR Cluster instance types for both master and core instances
    AllowedValues:
      - m5.xlarge
      - m4.xlarge
      - i3.xlarge
      - i3.2xlarge
      - r4.xlarge

Resources:
  NetworkingStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://emr-okta-blog.s3.amazonaws.com/templates/networking.yaml'
      Parameters:
        VpcCIDR: !Ref VpcCIDR
        PublicSubnet1CIDR: !Ref PublicSubnet1CIDR
        PublicSubnet2CIDR: !Ref PublicSubnet2CIDR
        PrivateSubnet1CIDR: !Ref PrivateSubnet1CIDR
        PrivateSubnet2CIDR: !Ref PrivateSubnet2CIDR

  LakeFormationStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://emr-okta-blog.s3.amazonaws.com/templates/lakeformation.yaml'
      Parameters:
        LFDatabaseName: !Ref LFDatabaseName
        LFTableName: !Ref LFTableName
        LFSAMLUserName: !Ref LFSAMLUserName
        SAMLProviderName: !Join ['-', [!Ref SAMLProviderName, !Select [4, !Split ['-', !Select [2, !Split ['/', !Ref AWS::StackId]]]]]]
        OktaAppMetadataURL: !Ref OktaAppMetadataURL

  EMRStack:
    Type: 'AWS::CloudFormation::Stack'
    Properties:
      TemplateURL: 'https://emr-okta-blog.s3.amazonaws.com/templates/emr.yaml'
      Parameters:
        EC2KeyPair: !Ref EC2KeyPair
        DataBucketName: !GetAtt 
          - LakeFormationStack
          - Outputs.DataBucketName
        DataBucketArn: !GetAtt 
          - LakeFormationStack
          - Outputs.DataBucketArn
        KdcAdminPassword: !Ref KdcAdminPassword
        ReleaseLabel: !Ref ReleaseLabel
        VpcId: !GetAtt 
          - NetworkingStack
          - Outputs.VpcId
        VpcSubnet: !GetAtt 
          - NetworkingStack
          - Outputs.PrivateSubnet1
        InstanceType: !Ref InstanceType
        HostedZoneId: !Ref HostedZoneId
        DomainName: !Ref DomainName
        PublicSubnet1Id: !GetAtt 
          - NetworkingStack
          - Outputs.PublicSubnet1
        PublicSubnet2Id: !GetAtt 
          - NetworkingStack
          - Outputs.PublicSubnet2
        SAMLProviderArn: !GetAtt
          - LakeFormationStack
          - Outputs.SAMLProviderArn
Outputs:
  OktaSingleSignOnUrl:
    Description: The value for Single sign on URL, to be updated in Okta
    Value: !GetAtt 
      - EMRStack
      - Outputs.OktaSingleSignOnUrl
  OktaRoleAttribute:
    Description: The value for the attribute statement https://aws.amazon.com/SAML/Attributes/Role, to be updated in Okta
    Value: !GetAtt 
      - EMRStack
      - Outputs.OktaRoleAttribute
  ZeppelinUrl:
    Description: Zeppelin URL
    Value: !GetAtt 
      - EMRStack
      - Outputs.ZeppelinUrl
  MasterNodeInstanceId:
    Description: EC2 instance ID of EMR master node
    Value: !GetAtt 
      - EMRStack
      - Outputs.MasterNodeInstanceId